name: Develop CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug apk with Gradle
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleDebug

      - name: Upload debug apk to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ${{github.workspace}}/app/build/outputs/apk/debug/*.apk
